export const Constants = {
  inSolution: "bg-mainframe-yellow",
  substringBackground: "bg-yellow-400",
  reverseSubstringBackground: "bg-sky-700",
  inPosition: "bg-mainframe-green",
  usedLetterBoard: "bg-lime-900 opacity-80",
  usedLetterKey: "bg-lime-900 opacity-70",
  hoverKey: "hover:bg-lime-900",
  defaultBackground: "",
  defaultTextColor: "text-zinc-800",
  highlightedTextColor: "text-lime-600",
  borderColor: "border-lime-600",
  wordLength: 5,
  maxNumGuesses: 6,
  keyboardClue1: "bg-lime-900 shadow-glow1 shadow-mainframe-green",
  keyboardClue2: "bg-lime-900 shadow-glow2 shadow-mainframe-green",
  keyboardClue3: "bg-lime-900 shadow-glow3 shadow-mainframe-green",
};
